### ISSUE TITLE
is raytopia alive? o.O

### ISSUE THREAD

**Issue by marekmaskarinec** [raytopianprojects/DECADE--#9]
@raytopianprojects are u ok?

**Comment by Kylogias** [comment]
Context for anyone who isn't in the Decade Jam discord: Raytopia mysteriously vanished around the time this issue was made. It is unknown why and for how long, but he did vanish sometime between Sunday 4 PM EST to Wednesday 10 AM EST

**Comment by Kylogias** [comment]
Found our answer!

![image](https://user-images.githubusercontent.com/45217130/120325253-7b64ba00-c2b5-11eb-9222-8faa9fd84e7b.png)
